<template>
    <div>
        <h2>Shamir Secret Sharing for people with friends</h2>
        <div>
            <p>Banana Split uses <a href="https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing">Shamir's secret sharing</a> to make your paper backups more resilient and secure.</p>
            <p>After you type in your secret into Banana Split, it will be encrypted with a autogenerated passphrase and split into N QR-codes, ready to be printed out. You'll need N/2+1 of those printouts to reconstruct the secret, and then the passphrase to decrypt it.</p>
            <p>Banana Split tries to protect your secret from the attack vectors like "attacker is able to intercept everything you're sending to your printer", and that's why you'll have to write down the passphrase on your printouts by hand.</p>
            <p>Banana Split is a self-contained HTML page, and should only be opened from your local Documents folder, while browser is in the Offline mode — this way the risk of compromise will be minimal.</p>
            <p>Recovery can be done on any device with a webcam — just show your QR codes to the webcam and follow the notifications on screen in the process.</p>
        </div>
    </div>
</template>

<script>
export default {
  name: 'Info',
}
</script>

<style>
</style>
