<template>
  <div class="general-info">
    <h2>What is this?</h2>
    <p>
      Banana Split is a self-contained HTML page, which makes your paper 
      backups more resilient and secure using 
      <a href="https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing" target="_blank">
        Shamir's secret sharing scheme</a>.
      You can encrypt and split particularly sensitive information 
      so that it's not physically stored in one place — your master 
      assword, seed phrase, etc.
    </p>
    <h2>How does it work?</h2>
    <p>
      After you type in your secret into Banana Split, it will be encrypted with 
      an autogenerated passphrase and split into N QR-codes, ready to be printed out. 
      You'll need N/2+1 of those printouts to reconstruct the secret, and 
      then the passphrase to decrypt it.
    </p>
    <p>
      Banana Split tries to protect your secret from the attack vectors like 
      "attacker is able to intercept everything you're sending to your printer", 
      and that's why you'll have to write down the passphrase on your printouts 
      by hand.
    </p>
    <p>
      Of course you should seal your printouts in non-transparent envelopes and distribute among different locations as soon as you're done writing your seed phrase — Banana Split is only more secure than a single paper with your secret as long as the secrets can't be lost/stolen altogether.
    </p>
    <p>
      All operations must be performed in Offline mode. Recovery can be done 
      on any device with a webcam — just show your QR codes to the webcam 
      and follow the notifications on screen in the process. 
    </p>
    <h2>How to use it?</h2>
    <ol>
      <li>Save this HTML page into your local Documents folder</li>
      <li>Turn off Wi-Fi, Bluetooth and any other connectivity on your device</li>
      <li>Open the downloaded HTML page and follow the instructions</li>
    </ol>
    <p>
      This way the risk of compromise will be minimal.
    </p>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "GeneralInfo",
});
</script>

<style>
.general-info {
  display: block;
  padding-bottom: 30px;
}
p {
  line-height: 1.5em;
}
li {
  padding-bottom: 0.5em;
}
</style>
