<template>
  <div class="qr-tile">
    <div class="print-only">
      <h1>{{ title }}</h1>
      <h3>
        You need {{ requiredShards - 1 }} more QR {{ pluralizeCode }} like this
        to reconstruct the secret
      </h3>
    </div>
    <qriously class="qr-code print-only" :value="shard" :size="600" />
    <qriously class="screen-only" :value="shard" :size="200" />
    <div class="print-only">
      <div class="recovery-field">
        <div class="recovery-title">
          Recovery&nbsp;passphrase&nbsp;is&nbsp;
        </div>
        <div class="recovery-blank" />
      </div>
      <p class="version">
        Please go to <a href="https://bs.parity.io">bs.parity.io</a> to download
        the reconstruction webapp, if you don't have one already. This has been
        generated by BananaSplit version {{ version }}, git revision
        {{ gitRevision }}
      </p>
    </div>
  </div>
</template>

<script>
import { version } from "../../package.json";
export default {
  name: "ShardQrCode",
  props: {
    title: {
      type: String,
      required: true
    },
    shard: {
      type: String,
      required: true
    },
    requiredShards: {
      type: Number,
      required: true
    }
  },
  computed: {
    pluralizeCode: function() {
      if (this.requiredShards - 1 === 1) {
        return "code";
      } else {
        return "codes";
      }
    },
    version: function() {
      return version;
    },
    gitRevision: function() {
      return process.env.GIT_REVISION;
    }
  }
};
</script>

<style>
@media screen {
  .print-only {
    display: none;
  }

  .qr-tile {
    display: inline-block;
  }
}

@media print {
  .screen-only {
    display: none;
  }

  .qr-tile {
    page-break-after: always;
  }

  canvas {
    height: min(80vw, 80vh);
    width: min(80vw, 80vh) !important;
  }

  @page {
    margin: 0;
    padding: 0;
  }
}
/*
@media print and (min-width: 20cm) {
  .qr-tile {
    text-align: left !important;
  }

  .print-only {
    padding: 0 10% 0 50% !important;
  }

  .qr-code {
    position: absolute;
    left: 0;
    top: 0;
    padding: 5% !important;
  }

  canvas {
    height: min(75vw, 75vh) !important;
    width: min(75vw, 75vh) !important;
  }
} */

.qr-tile {
  position: relative;
  font-family: "Avenir Next Condensed", "Avenir", Helvetica, Arial, sans-serif;
  margin: 0 auto;
  padding: 0;
  text-align: center;
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100vw;
  height: 100vh;
}

h1 {
  font-weight: 600;
  font-size: 1.5em;
}

canvas {
  margin: 0 auto;
  display: block;
}

h3,
h4 {
  font-weight: 400;
  margin: 0.25em 0 0 0;
}

.recovery-field {
  width: 100%;
  display: flex;
  margin-top: 2em;
  text-transform: uppercase;
}

.recovery-blank {
  width: 100%;
  border-bottom: 1px solid black;
}

.version {
  font-weight: 500;
  font-size: 75%;
  color: darkgray;
}
</style>
