<template>
  <div class="qr-tile">
    <div class="print-only">
      <h1>{{ title }}</h1>
      <h3>
        You need {{ requiredShards - 1 }} more QR {{ pluralizeCode }} like this
        to reconstruct the secret
      </h3>
      <h4>
        Please go to <a href="https://bs.parity.io">https://bs.parity.io</a> to
        download the reconstruction webapp, if you don't have one already
      </h4>
    </div>
    <qriously class="print-only" v-bind:value="shard" v-bind:size="600" />
    <qriously class="screen-only" v-bind:value="shard" v-bind:size="200" />
    <div class="print-only">
      <div class="recovery-field">
        <div class="recovery-title">Recovery&nbsp;passphrase&nbsp;is&nbsp;</div>
        <div class="recovery-blank" />
      </div>
      <p class="version">
        This has been generated by BananaSplit version {{ version }}, git
        revision {{ gitRevision }}
      </p>
    </div>
  </div>
</template>

<script>
import { version } from "../../package.json";
export default {
  name: "ShardQrCode",
  props: {
    title: String,
    shard: String,
    requiredShards: Number
  },
  computed: {
    pluralizeCode: function() {
      if (this.requiredShards - 1 === 1) {
        return "code";
      } else {
        return "codes";
      }
    },
    version: function() {
      return version;
    },
    gitRevision: function() {
      return process.env.GIT_REVISION;
    }
  }
};
</script>

<style>
@media screen {
  .print-only {
    display: none;
  }

  .qr-tile {
    display: inline-block;
  }
}

@media print {
  .screen-only {
    display: none;
  }

  .qr-tile {
    page-break-after: always;
  }
}

.qr-tile {
  font-family: "Avenir Next Condensed", "Avenir", Helvetica, Arial, sans-serif;
  margin: 0.1cm;
  padding: 0.5cm;
  border: dotted 1px rgba(0, 0, 0, 0.25);
  text-align: center;
}

h1 {
  font-weight: 600;
  font-size: 2em;
}

canvas {
  margin: 0 auto;
}

h3,
h4 {
  font-weight: 400;
}

.recovery-field {
  width: 100%;
  display: flex;
  margin-top: 2em;
  text-transform: uppercase;
}

.recovery-blank {
  width: 100%;
  border-bottom: 1px solid black;
}

.version {
  font-style: italic;
  color: darkgray;
}
</style>
